// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sndietcedhahiktsdvbw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuZGlldGNlZGhhaGlrdHNkdmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5OTQ4MTcsImV4cCI6MjA2ODU3MDgxN30.jBKWPQRWBKmcjTvLcRKT8xH0L7uiGYzUnMqb16DX270";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});